# Generated by Django 2.2.28 on 2022-10-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addresswooblhzprw'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresswooblhzprw',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
